### ISSUE TITLE
Background set to light mode in Gvim

### ISSUE THREAD

**Issue by Anmol42** [atahabaki/archman-vim#1]
I installed the theme and added it to my runtimepath.
It works perfectly in terminal vim but in Gvim somehow its background is set to white and doesn't change even upon using :set background=dark
Pls resolve it

**Comment by atahabaki** [comment]
This vim theme is not using any background color. The main idea here is to achieve KDE's native blur effect looks cool with vim.

And I have to say this theme based on Panic. Use it if you want background color. I hope this helps.

If you've read the README you'd not asked that.

Thanks and have a great day.

**Comment by Anmol42** [comment]
I am sorry for the disturbance.

I just found it out after I had submitted the issue and I have already
changed it in my machine.

Stay safe in these times.

**Comment by atahabaki** [comment]
Don't be sorry. There's nothing to be sorry. You just said I've faced an issue that looks issue for me. It's just that.

Thanks for your attention, really. Stay safe you too...
